/*
 * Copyright 2015-2026 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {PluginSpecification} from '@valtimo/plugin';
import {GITHUB_PLUGIN_LOGO_BASE64} from './assets';
import {GitHubConfigurationComponent} from './components/github-configuration/github-configuration.component';
import {GetRepositoryConfigurationComponent} from './components/get-repository/get-repository-configuration.component';
import {ListRepositoriesConfigurationComponent} from './components/list-repositories/list-repositories-configuration.component';
import {GetAuthenticatedUserConfigurationComponent} from './components/get-authenticated-user/get-authenticated-user-configuration.component';
import {ListIssuesConfigurationComponent} from './components/list-issues/list-issues-configuration.component';
import {GetIssueConfigurationComponent} from './components/get-issue/get-issue-configuration.component';
import {SearchIssuesConfigurationComponent} from './components/search-issues/search-issues-configuration.component';
import {CreateIssueConfigurationComponent} from './components/create-issue/create-issue-configuration.component';
import {UpdateIssueConfigurationComponent} from './components/update-issue/update-issue-configuration.component';
import {CommentConfigurationComponent} from './components/comment/comment-configuration.component';
import {ListPullRequestsConfigurationComponent} from './components/list-pull-requests/list-pull-requests-configuration.component';
import {GetPullRequestConfigurationComponent} from './components/get-pull-request/get-pull-request-configuration.component';
import {CreatePullRequestConfigurationComponent} from './components/create-pull-request/create-pull-request-configuration.component';
import {UpdatePullRequestConfigurationComponent} from './components/update-pull-request/update-pull-request-configuration.component';
import {SetPullRequestDraftConfigurationComponent} from './components/set-pull-request-draft/set-pull-request-draft-configuration.component';
import {MergePullRequestConfigurationComponent} from './components/merge-pull-request/merge-pull-request-configuration.component';
import {ReviewPullRequestConfigurationComponent} from './components/review-pull-request/review-pull-request-configuration.component';
import {RequestReviewersConfigurationComponent} from './components/request-reviewers/request-reviewers-configuration.component';
import {ListReviewThreadsConfigurationComponent} from './components/list-review-threads/list-review-threads-configuration.component';
import {ReplyToReviewCommentConfigurationComponent} from './components/reply-to-review-comment/reply-to-review-comment-configuration.component';
import {ResolveReviewThreadConfigurationComponent} from './components/resolve-review-thread/resolve-review-thread-configuration.component';
import {CreateLabelConfigurationComponent} from './components/create-label/create-label-configuration.component';
import {GetCheckStatusConfigurationComponent} from './components/get-check-status/get-check-status-configuration.component';
import {ListWorkflowRunsConfigurationComponent} from './components/list-workflow-runs/list-workflow-runs-configuration.component';
import {GetWorkflowRunConfigurationComponent} from './components/get-workflow-run/get-workflow-run-configuration.component';
import {GetJobLogsConfigurationComponent} from './components/get-job-logs/get-job-logs-configuration.component';
import {RerunWorkflowConfigurationComponent} from './components/rerun-workflow/rerun-workflow-configuration.component';
import {GetFileContentConfigurationComponent} from './components/get-file-content/get-file-content-configuration.component';
import {CreateOrUpdateFileConfigurationComponent} from './components/create-or-update-file/create-or-update-file-configuration.component';
import {CreateBranchConfigurationComponent} from './components/create-branch/create-branch-configuration.component';
import {GetProjectItemsConfigurationComponent} from './components/get-project-items/get-project-items-configuration.component';
import {SetProjectItemFieldConfigurationComponent} from './components/set-project-item-field/set-project-item-field-configuration.component';
import {RestRequestConfigurationComponent} from './components/rest-request/rest-request-configuration.component';
import {GraphqlQueryConfigurationComponent} from './components/graphql-query/graphql-query-configuration.component';

const githubPluginSpecification: PluginSpecification = {
  pluginId: 'github',
  pluginConfigurationComponent: GitHubConfigurationComponent,
  pluginLogoBase64: GITHUB_PLUGIN_LOGO_BASE64,
  functionConfigurationComponents: {
    'get-repository': GetRepositoryConfigurationComponent,
    'list-repositories': ListRepositoriesConfigurationComponent,
    'get-authenticated-user': GetAuthenticatedUserConfigurationComponent,
    'list-issues': ListIssuesConfigurationComponent,
    'get-issue': GetIssueConfigurationComponent,
    'search-issues': SearchIssuesConfigurationComponent,
    'create-issue': CreateIssueConfigurationComponent,
    'update-issue': UpdateIssueConfigurationComponent,
    'comment': CommentConfigurationComponent,
    'list-pull-requests': ListPullRequestsConfigurationComponent,
    'get-pull-request': GetPullRequestConfigurationComponent,
    'create-pull-request': CreatePullRequestConfigurationComponent,
    'update-pull-request': UpdatePullRequestConfigurationComponent,
    'set-pull-request-draft': SetPullRequestDraftConfigurationComponent,
    'merge-pull-request': MergePullRequestConfigurationComponent,
    'review-pull-request': ReviewPullRequestConfigurationComponent,
    'request-reviewers': RequestReviewersConfigurationComponent,
    'list-review-threads': ListReviewThreadsConfigurationComponent,
    'reply-to-review-comment': ReplyToReviewCommentConfigurationComponent,
    'resolve-review-thread': ResolveReviewThreadConfigurationComponent,
    'create-label': CreateLabelConfigurationComponent,
    'get-check-status': GetCheckStatusConfigurationComponent,
    'list-workflow-runs': ListWorkflowRunsConfigurationComponent,
    'get-workflow-run': GetWorkflowRunConfigurationComponent,
    'get-job-logs': GetJobLogsConfigurationComponent,
    'rerun-workflow': RerunWorkflowConfigurationComponent,
    'get-file-content': GetFileContentConfigurationComponent,
    'create-or-update-file': CreateOrUpdateFileConfigurationComponent,
    'create-branch': CreateBranchConfigurationComponent,
    'get-project-items': GetProjectItemsConfigurationComponent,
    'set-project-item-field': SetProjectItemFieldConfigurationComponent,
    'rest-request': RestRequestConfigurationComponent,
    'graphql-query': GraphqlQueryConfigurationComponent,
  },
  pluginTranslations: {
    nl: {
      title: 'GitHub',
      description:
        'Lees en schrijf GitHub vanuit een proces: issues, pull requests, reviews, checks, bestanden en projectborden.',
      configurationTitle: 'Configuratienaam',
      configurationTitleTooltip:
        'De naam van de huidige plugin-configuratie. Onder deze naam is de configuratie in de rest van de applicatie terug te vinden.',
      url: 'GitHub API-URL',
      urlTooltip:
        'https://api.github.com voor github.com. Voor GitHub Enterprise Server is dit https://jouw-host/api/v3.',
      token: 'Token',
      tokenTooltip:
        'Alles wat dit token mag, mag elk proces dat aan deze configuratie gekoppeld is. Geef een configuratie die alleen leest dus ook een token dat alleen leest.',
      defaultRepository: 'Standaard repository',
      defaultRepositoryTooltip:
        'Wordt gebruikt door elke actie die zelf geen repository invult. Laat leeg voor een configuratie die over meerdere repositories werkt.',
      graphqlUrl: 'GraphQL-URL',
      graphqlUrlTooltip:
        'Laat leeg om af te leiden uit de API-URL. Dat klopt voor github.com en voor Enterprise Server.',
      perPage: 'Items per pagina',
      perPageTooltip: 'Hoeveel items per aanvraag bij GitHub worden opgehaald. GitHub staat maximaal 100 toe.',
      maxPages: "Maximum aantal pagina's per actie",
      maxPagesTooltip:
        "Begrenst hoeveel pagina's één lijstactie leest. Wordt de grens geraakt, dan staat truncated in het resultaat op true — een lijst die vroegtijdig stopte ziet er anders uit als een korte lijst.",
      'get-repository': "Repository ophalen",
      getRepositoryDescription: "Leest een repository: de standaardbranch, of hij privé is en of hij gearchiveerd is.",
      'list-repositories': "Repositories opsommen",
      listRepositoriesDescription: "Somt de repositories van een organisatie of gebruiker op.",
      'get-authenticated-user': "Ingelogde gebruiker ophalen",
      getAuthenticatedUserDescription: "Meldt bij welk account het token van deze configuratie hoort. Handig om te controleren of een configuratie werkt.",
      'list-issues': "Issues opsommen",
      listIssuesDescription: "Somt de issues van een repository op. Open pull requests komen ook terug — elk item zegt onder isPullRequest wat het is.",
      'get-issue': "Issue ophalen",
      getIssueDescription: "Leest één issue, eventueel met de reacties en de tijdlijn.",
      'search-issues': "Issues en pull requests zoeken",
      searchIssuesDescription: "Voert een zoekopdracht uit over meerdere repositories, in de zoeksyntax van GitHub zelf.",
      'create-issue': "Issue aanmaken",
      createIssueDescription: "Opent een nieuw issue.",
      'update-issue': "Issue bijwerken",
      updateIssueDescription: "Werkt een issue bij, en voegt labels en toewijzingen toe of haalt ze weg. Alles wat leeg blijft, blijft zoals het is.",
      'comment': "Reageren op issue of pull request",
      commentDescription: "Plaatst een reactie. Een pull request vul je hier net zo in als een issue.",
      'list-pull-requests': "Pull requests opsommen",
      listPullRequestsDescription: "Somt de pull requests van één repository op.",
      'get-pull-request': "Pull request ophalen",
      getPullRequestDescription: "Leest één pull request, eventueel met de gewijzigde bestanden, reviews, reacties en checkstatus.",
      'create-pull-request': "Pull request aanmaken",
      createPullRequestDescription: "Opent een pull request vanaf een branch die al bestaat.",
      'update-pull-request': "Pull request bijwerken",
      updatePullRequestDescription: "Werkt een pull request bij, en voegt labels toe of haalt ze weg. Alles wat leeg blijft, blijft zoals het is.",
      'set-pull-request-draft': "Pull request klaarzetten of terug naar concept",
      setPullRequestDraftDescription: "Zet een pull request tussen concept en klaar voor review.",
      'merge-pull-request': "Pull request mergen",
      mergePullRequestDescription: "Merget een pull request.",
      'review-pull-request': "Pull request reviewen",
      reviewPullRequestDescription: "Keurt een pull request goed, vraagt wijzigingen of plaatst een opmerking. GitHub staat niemand toe zijn eigen pull request goed te keuren.",
      'request-reviewers': "Reviewers vragen",
      requestReviewersDescription: "Vraagt personen of teams om een pull request te reviewen.",
      'list-review-threads': "Reviewthreads ophalen",
      listReviewThreadsDescription: "Leest de reviewgesprekken bij de regels van een pull request, elk met de vraag of het is opgelost.",
      'reply-to-review-comment': "Antwoorden op reviewreactie",
      replyToReviewCommentDescription: "Antwoordt een reviewer in diens eigen thread, in plaats van als nieuwe reactie onderaan.",
      'resolve-review-thread': "Reviewthread oplossen",
      resolveReviewThreadDescription: "Markeert een reviewgesprek als opgelost, of heropent het.",
      'create-label': "Label aanmaken",
      createLabelDescription: "Maakt een label aan. Een label dat er al is wordt gerapporteerd zoals het is in plaats van te falen, dus dit kan elke keer draaien.",
      'get-check-status': "Checkstatus ophalen",
      getCheckStatusDescription: "Meldt of een commit groen is, over zowel check runs als commit statuses. Een commit die niemand heeft gebouwd meldt none, niet success.",
      'list-workflow-runs': "Workflow-runs opsommen",
      listWorkflowRunsDescription: "Somt de GitHub Actions-runs van een repository op.",
      'get-workflow-run': "Workflow-run ophalen",
      getWorkflowRunDescription: "Leest één Actions-run, eventueel met de jobs en welke stappen daarvan misgingen.",
      'get-job-logs': "Joblogboek ophalen",
      getJobLogsDescription: "Leest het staartje van het logboek van één job — daar staat waarom een job faalde.",
      'rerun-workflow': "Workflow opnieuw uitvoeren",
      rerunWorkflowDescription: "Voert een Actions-run opnieuw uit, standaard alleen de gefaalde jobs.",
      'get-file-content': "Bestandsinhoud ophalen",
      getFileContentDescription: "Leest een bestand uit een repository, of toont de inhoud van een map. Een bestand dat geen tekst is komt terug als base64.",
      'create-or-update-file': "Bestand aanmaken of bijwerken",
      createOrUpdateFileDescription: "Commit een bestand direct op een branch, zonder pull request ertussen.",
      'create-branch': "Branch aanmaken",
      createBranchDescription: "Takt af van een andere ref. Een branch die al bestaat wordt gerapporteerd zoals hij is in plaats van te falen.",
      'get-project-items': "Projectitems ophalen",
      getProjectItemsDescription: "Leest de projectkaarten waarop een issue staat, met alle veldwaarden — sprint, status, schatting. De ids die nodig zijn om een veld terug te schrijven komen hiervandaan.",
      'set-project-item-field': "Projectveld instellen",
      setProjectItemFieldDescription: "Stelt één veld op één projectkaart in.",
      'rest-request': "REST-aanvraag",
      restRequestDescription: "Roept elk GitHub REST-endpoint aan, voor alles wat de andere acties niet dekken. Het antwoord wordt opgeslagen zoals GitHub het stuurde, zonder inkorten.",
      'graphql-query': "GraphQL-query",
      graphqlQueryDescription: "Voert elk GitHub GraphQL-document uit. De data wordt opgeslagen zoals GitHub die stuurde, zonder inkorten.",

      repository: "Repository",
      repositoryTooltip: "Laat leeg om de standaard repository van deze pluginconfiguratie te gebruiken. Accepteert een procesvariabele, bijvoorbeeld pv:targetRepository.",
      resultVariable: "Resultaatvariabele",
      resultVariableTooltip: "Naam van de procesvariabele waarin het antwoord wordt opgeslagen. Laat leeg om het antwoord niet te bewaren.",
      owner: "Eigenaar",
      ownerTooltip: "Een organisatie of een gebruiker.",
      type: "Soort",
      typeTooltip: "Welke repositories van deze eigenaar getoond worden.",
      "type.all": "Alle",
      "type.public": "Openbaar",
      "type.private": "Privé",
      "type.forks": "Forks",
      "type.sources": "Bronnen",
      "type.member": "Lid van",
      limit: "Maximum aantal resultaten",
      limitTooltip: "Stopt met lezen zodra dit aantal is bereikt. Laat leeg voor het paginabudget van de configuratie.",
      state: "Status",
      stateTooltip: "Welke issues meegenomen worden.",
      "state.open": "Open",
      "state.closed": "Gesloten",
      "state.all": "Alle",
      labels: "Labels",
      labelsTooltip: "Door komma's gescheiden. Bij een lijstactie filtert dit: alleen issues met álle genoemde labels komen terug.",
      assignee: "Toegewezen aan",
      assigneeTooltip: "Een GitHub-login. Gebruik none voor issues zonder toewijzing, of * voor alle.",
      creator: "Aangemaakt door",
      creatorTooltip: "Een GitHub-login.",
      since: "Gewijzigd sinds",
      sinceTooltip: "Alleen issues die na dit moment zijn bijgewerkt, als ISO 8601-tijdstempel.",
      issueNumber: "Issuenummer",
      issueNumberTooltip: "Het nummer uit de issue-URL. Een pull request heeft er ook een, en die werkt hier ook.",
      includeComments: "Reacties meenemen",
      includeCommentsTooltip: "Kost een extra aanroep, en levert bij een lange discussie veel tekst op.",
      includeTimeline: "Tijdlijn meenemen",
      includeTimelineTooltip: "Labelwijzigingen, kruisverwijzingen en commits. Hier is te zien of er al een pull request voor dit issue bestaat.",
      query: "Zoekopdracht",
      queryTooltip: "De zoeksyntax van GitHub zelf. Let op: de zoekindex loopt tot enkele minuten achter op wijzigingen.",
      sort: "Sorteren op",
      sortTooltip: "Bijvoorbeeld created, updated of comments. Laat leeg voor beste overeenkomst.",
      order: "Volgorde",
      orderTooltip: "Heeft alleen effect samen met een sorteerveld.",
      "order.": "Ongewijzigd laten",
      "order.desc": "Aflopend",
      "order.asc": "Oplopend",
      issueTitle: "Titel",
      issueTitleTooltip: "De titel.",
      body: "Tekst",
      bodyTooltip: "Markdown. Meestal een procesvariabele, bijvoorbeeld pv:reviewReply.",
      newLabels: "Labels",
      newLabelsTooltip: "Door komma's gescheiden.",
      assignees: "Toegewezen aan",
      assigneesTooltip: "Door komma's gescheiden GitHub-logins.",
      newTitle: "Titel",
      newTitleTooltip: "Laat leeg om de titel ongewijzigd te laten.",
      newBody: "Tekst",
      newBodyTooltip: "Markdown. Laat leeg om de omschrijving ongewijzigd te laten.",
      newState: "Nieuwe status",
      newStateTooltip: "Laat leeg om de status ongewijzigd te laten. Sluiten is hier niet hetzelfde als mergen.",
      "state.": "Ongewijzigd laten",
      stateReason: "Reden",
      stateReasonTooltip: "Waarom het issue gesloten of heropend wordt.",
      "stateReason.": "Ongewijzigd laten",
      "stateReason.completed": "Afgerond",
      "stateReason.not_planned": "Niet gepland",
      "stateReason.reopened": "Heropend",
      addLabels: "Labels toevoegen",
      addLabelsTooltip: "Door komma's gescheiden. Worden toegevoegd aan wat er al staat; bestaande labels blijven.",
      removeLabels: "Labels verwijderen",
      removeLabelsTooltip: "Door komma's gescheiden. Een label dat er niet is, is geen fout.",
      addAssignees: "Toewijzingen toevoegen",
      addAssigneesTooltip: "Door komma's gescheiden GitHub-logins.",
      removeAssignees: "Toewijzingen verwijderen",
      removeAssigneesTooltip: "Door komma's gescheiden GitHub-logins.",
      prState: "Status",
      prStateTooltip: "Welke pull requests meegenomen worden.",
      baseFilter: "Doelbranch",
      baseFilterTooltip: "Filtert op de branch waar de wijzigingen naartoe gaan.",
      headFilter: "Bronbranch",
      headFilterTooltip: "Filtert op de branch waar de wijzigingen vandaan komen.",
      pullRequestNumber: "Pull-requestnummer",
      pullRequestNumberTooltip: "Het nummer uit de pull-request-URL.",
      includeFiles: "Gewijzigde bestanden meenemen",
      includeFilesTooltip: "Bestandsnamen en regelaantallen, niet de diff zelf.",
      includeReviews: "Reviews meenemen",
      includeReviewsTooltip: "De goedkeuringen en wijzigingsverzoeken, met de tekst die erbij is getypt.",
      includeChecks: "Checkstatus meenemen",
      includeChecksTooltip: "Of de head-commit groen is, over check runs en commit statuses heen.",
      head: "Bronbranch",
      headTooltip: "De branch met de wijzigingen. Die moet bestaan en voorlopen op de doelbranch.",
      base: "Doelbranch",
      baseTooltip: "Laat leeg voor de standaardbranch van de repository zelf — die heet niet overal main.",
      draft: "Concept",
      draftTooltip: "Een concept-pull-request kan niet gemerged worden en vraagt niemand om review.",
      newBase: "Doelbranch",
      newBaseTooltip: "Laat leeg om de doelbranch ongewijzigd te laten.",
      draftState: "Concept",
      draftStateTooltip: "Aan zet de pull request terug naar concept; uit markeert hem klaar voor review.",
      mergeMethod: "Mergemethode",
      mergeMethodTooltip: "De methode moet door de repository toegestaan zijn, anders weigert GitHub de merge.",
      "mergeMethod.merge": "Mergecommit",
      "mergeMethod.squash": "Samenvoegen en mergen",
      "mergeMethod.rebase": "Rebasen en mergen",
      commitTitle: "Committitel",
      commitTitleTooltip: "Laat leeg voor de titel die GitHub zelf zou maken.",
      commitMessage: "Commitbericht",
      commitMessageTooltip: "Laat leeg voor het bericht dat GitHub zelf zou maken.",
      expectedHeadSha: "Verwachte head-commit",
      expectedHeadShaTooltip: "De moeite waard: GitHub weigert de merge als de branch sinds het laatste lezen is verplaatst, in plaats van een commit te mergen die niemand heeft gezien.",
      event: "Oordeel",
      eventTooltip: "Wat voor soort review wordt ingediend.",
      "event.APPROVE": "Goedkeuren",
      "event.REQUEST_CHANGES": "Wijzigingen vragen",
      "event.COMMENT": "Opmerking",
      reviewBody: "Tekst",
      reviewBodyTooltip: "Verplicht bij een opmerking of wijzigingsverzoek; optioneel bij een goedkeuring.",
      reviewers: "Reviewers",
      reviewersTooltip: "Door komma's gescheiden GitHub-logins. Iemand kan niet om review van zijn eigen pull request gevraagd worden.",
      teamReviewers: "Reviewende teams",
      teamReviewersTooltip: "Door komma's gescheiden team-slugs, zonder de organisatie.",
      onlyUnresolved: "Alleen onopgeloste",
      onlyUnresolvedTooltip: "Laat aanstaan om openstaande feedback af te werken: anders komen dezelfde beantwoorde opmerkingen elke ronde terug.",
      commentId: "Reactie",
      commentIdTooltip: "Het numerieke id van een reactie in de thread, zoals teruggegeven door Reviewthreads ophalen.",
      threadId: "Thread",
      threadIdTooltip: "Het id van de thread, zoals teruggegeven door Reviewthreads ophalen. Niet hetzelfde als een reactie-id.",
      resolve: "Oplossen",
      resolveTooltip: "Aan markeert het gesprek als opgelost; uit heropent het.",
      name: "Naam",
      nameTooltip: "De labelnaam, precies zoals die moet verschijnen.",
      color: "Kleur",
      colorTooltip: "Zes hexadecimale tekens. Een # ervoor mag en wordt weggelaten.",
      labelDescription: "Omschrijving",
      labelDescriptionTooltip: "Wordt getoond als iemand over het label beweegt.",
      ref: "Commit, branch of tag",
      refTooltip: "Een commit-sha is het precieze antwoord; een branchnaam rapporteert wat er op dit moment bovenaan staat.",
      branch: "Branch",
      branchTooltip: "Filtert op de branch waarvoor de run was.",
      runStatus: "Status",
      runStatusTooltip: "Bijvoorbeeld completed, in_progress, failure of success.",
      runEvent: "Gestart door",
      runEventTooltip: "Filtert op wat de run startte, bijvoorbeeld push of pull_request.",
      runId: "Run",
      runIdTooltip: "Het numerieke id van de workflow-run.",
      includeJobs: "Jobs meenemen",
      includeJobsTooltip: "Voegt alle jobs van de run toe, en apart de gefaalde jobs met de stappen die misgingen.",
      jobId: "Job",
      jobIdTooltip: "Het numerieke id van de job, zoals teruggegeven door Workflow-run ophalen.",
      maxLines: "Aantal regels",
      maxLinesTooltip: "Het staartje van het log wordt bewaard: een gefaalde job zegt onderaan waaróm.",
      onlyFailed: "Alleen gefaalde jobs",
      onlyFailedTooltip: "Uit voert de hele workflow opnieuw uit, wat de volledige build kost.",
      path: "Pad",
      pathTooltip: "Relatief aan de root van de repository. Bij een map worden de items getoond.",
      fileRef: "Commit, branch of tag",
      fileRefTooltip: "Laat leeg voor de standaardbranch van de repository.",
      writePath: "Pad",
      writePathTooltip: "Relatief aan de root van de repository. Onderliggende mappen worden aangemaakt.",
      content: "Inhoud",
      contentTooltip: "De tekst die gecommit wordt. Gebruik een resource voor alles wat geen tekst is.",
      resourceId: "Resource",
      resourceIdTooltip: "Een bestand in tijdelijke opslag, via een procesvariabele. Zo commit je een afbeelding. Geef dit óf inhoud, niet allebei.",
      writeBranch: "Branch",
      writeBranchTooltip: "Laat leeg voor de standaardbranch van de repository. De commit komt er direct op te staan, zonder pull request ertussen.",
      expectedSha: "Verwachte blob-sha",
      expectedShaTooltip: "Laat leeg om het bestaande bestand op te zoeken en te vervangen. Vul in om te weigeren als het bestand sinds het lezen is gewijzigd.",
      branchName: "Branchnaam",
      branchNameTooltip: "Zonder refs/heads/. Een branch die al bestaat wordt gerapporteerd zoals hij is, en is geen fout.",
      fromRef: "Aftakken van",
      fromRefTooltip: "Een branch, tag of commit. Laat leeg voor de standaardbranch van de repository.",
      projectId: "Project",
      projectIdTooltip: "Het node-id van het project, zoals teruggegeven door Projectitems ophalen.",
      itemId: "Kaart",
      itemIdTooltip: "Het node-id van de kaart op het bord, zoals teruggegeven door Projectitems ophalen.",
      fieldId: "Veld",
      fieldIdTooltip: "Het node-id van het veld, zoals teruggegeven door Projectitems ophalen.",
      valueType: "Soort waarde",
      valueTypeTooltip: "Een keuzelijst en een iteratie nemen het id van de optie, niet het label.",
      "valueType.text": "Tekst",
      "valueType.number": "Getal",
      "valueType.date": "Datum",
      "valueType.singleSelectOptionId": "Keuzelijstoptie",
      "valueType.iterationId": "Iteratie",
      value: "Waarde",
      valueTooltip: "Waarop het veld gezet wordt.",
      method: "Methode",
      methodTooltip: "Laat op GET staan om te lezen.",
      "method.GET": "GET (lezen)",
      "method.POST": "POST",
      "method.PATCH": "PATCH",
      "method.PUT": "PUT",
      "method.DELETE": "DELETE",
      restPath: "Pad",
      restPathTooltip: "Relatief aan de REST-root van deze configuratie, bijvoorbeeld /repos/ritense/coworker-plugin/releases.",
      restBody: "Body",
      restBodyTooltip: "JSON. Laat leeg voor een aanvraag zonder body.",
      graphqlQuery: "Query",
      graphqlQueryTooltip: "Een GraphQL-query of -mutatie.",
      variables: "Variabelen",
      variablesTooltip: "JSON-object met de variabelen van de query. Laat leeg voor een query zonder variabelen.",
    },
    en: {
      title: 'GitHub',
      description:
        'Read and write GitHub from a process: issues, pull requests, reviews, checks, files and project boards.',
      configurationTitle: 'Configuration name',
      configurationTitleTooltip:
        'The name of the current plugin configuration. Under this name, the configuration can be found in the rest of the application.',
      url: 'GitHub API url',
      urlTooltip:
        'https://api.github.com for github.com. For GitHub Enterprise Server this is https://your-host/api/v3.',
      token: 'Token',
      tokenTooltip:
        'Whatever this token may do, every process linked to this configuration may do. Give a configuration that only reads a token that only reads.',
      defaultRepository: 'Default repository',
      defaultRepositoryTooltip:
        'Used by every action that does not name a repository of its own. Leave empty for a configuration that works across repositories.',
      graphqlUrl: 'GraphQL url',
      graphqlUrlTooltip:
        'Leave empty to derive it from the API url, which is right for github.com and for Enterprise Server.',
      perPage: 'Items per page',
      perPageTooltip: 'How many items are read per request to GitHub. GitHub caps this at 100.',
      maxPages: 'Maximum pages per action',
      maxPagesTooltip:
        'Caps how many pages one list action reads. Reaching the cap sets truncated to true in the result — a list that stopped early otherwise looks exactly like a short one.',
      'get-repository': "Get repository",
      getRepositoryDescription: "Reads a repository: its default branch, whether it is private and whether it is archived.",
      'list-repositories': "List repositories",
      listRepositoriesDescription: "Lists the repositories of an organisation or a user.",
      'get-authenticated-user': "Get authenticated user",
      getAuthenticatedUserDescription: "Reports which account the token of this configuration belongs to. Useful to check a configuration works.",
      'list-issues': "List issues",
      listIssuesDescription: "Lists the issues of a repository. Open pull requests come back too — each item says which it is under isPullRequest.",
      'get-issue': "Get issue",
      getIssueDescription: "Reads one issue, optionally with its comments and its timeline.",
      'search-issues': "Search issues and pull requests",
      searchIssuesDescription: "Runs a query across repositories, in GitHub's own search syntax.",
      'create-issue': "Create issue",
      createIssueDescription: "Opens a new issue.",
      'update-issue': "Update issue",
      updateIssueDescription: "Edits an issue, and adds or removes labels and assignees. Everything left empty stays as it is.",
      'comment': "Comment on issue or pull request",
      commentDescription: "Posts a comment. A pull request takes its number here just like an issue does.",
      'list-pull-requests': "List pull requests",
      listPullRequestsDescription: "Lists the pull requests of one repository.",
      'get-pull-request': "Get pull request",
      getPullRequestDescription: "Reads one pull request, optionally with its changed files, reviews, comments and check status.",
      'create-pull-request': "Create pull request",
      createPullRequestDescription: "Opens a pull request from a branch that already exists.",
      'update-pull-request': "Update pull request",
      updatePullRequestDescription: "Edits a pull request, and adds or removes labels. Everything left empty stays as it is.",
      'set-pull-request-draft': "Mark pull request ready or draft",
      setPullRequestDraftDescription: "Moves a pull request between draft and ready for review.",
      'merge-pull-request': "Merge pull request",
      mergePullRequestDescription: "Merges a pull request.",
      'review-pull-request': "Review pull request",
      reviewPullRequestDescription: "Approves, requests changes on, or comments on a pull request. GitHub does not let anybody approve their own.",
      'request-reviewers': "Request reviewers",
      requestReviewersDescription: "Asks people or teams to review a pull request.",
      'list-review-threads': "List review threads",
      listReviewThreadsDescription: "Reads the inline review conversations of a pull request, each with whether it has been resolved.",
      'reply-to-review-comment': "Reply to review comment",
      replyToReviewCommentDescription: "Answers a reviewer inside their own thread, rather than as a new comment at the bottom.",
      'resolve-review-thread': "Resolve review thread",
      resolveReviewThreadDescription: "Marks a review conversation resolved, or reopens it.",
      'create-label': "Create label",
      createLabelDescription: "Creates a label. A label that is already there is reported as it stands rather than failing, so this is safe to run every time.",
      'get-check-status': "Get check status",
      getCheckStatusDescription: "Reports whether a commit is green, across both check runs and commit statuses. A commit nobody built reports none rather than success.",
      'list-workflow-runs': "List workflow runs",
      listWorkflowRunsDescription: "Lists GitHub Actions runs of a repository.",
      'get-workflow-run': "Get workflow run",
      getWorkflowRunDescription: "Reads one Actions run, optionally with its jobs and which of their steps failed.",
      'get-job-logs': "Get job logs",
      getJobLogsDescription: "Reads the tail of one job's log, which is where a failing job says why.",
      'rerun-workflow': "Re-run workflow",
      rerunWorkflowDescription: "Re-runs an Actions run, by default only the jobs that failed.",
      'get-file-content': "Get file content",
      getFileContentDescription: "Reads a file out of a repository, or lists a directory. A file that is not text comes back as base64.",
      'create-or-update-file': "Create or update file",
      createOrUpdateFileDescription: "Commits a file straight to a branch, with no pull request in between.",
      'create-branch': "Create branch",
      createBranchDescription: "Branches off another ref. A branch that already exists is reported as it stands rather than failing.",
      'get-project-items': "Get project items",
      getProjectItemsDescription: "Reads the project cards an issue sits on, with every field value on each — sprint, status, estimate. The ids needed to write a field back come from here.",
      'set-project-item-field': "Set project item field",
      setProjectItemFieldDescription: "Sets one field on one project card.",
      'rest-request': "REST request",
      restRequestDescription: "Calls any GitHub REST endpoint, for anything the other actions do not cover. The answer is stored exactly as GitHub sent it, not trimmed.",
      'graphql-query': "GraphQL query",
      graphqlQueryDescription: "Runs any GitHub GraphQL document. The data is stored exactly as GitHub sent it, not trimmed.",

      repository: "Repository",
      repositoryTooltip: "Leave empty to use the default repository of this plugin configuration. Takes a process variable, for example pv:targetRepository.",
      resultVariable: "Result variable",
      resultVariableTooltip: "Name of the process variable the answer is stored in. Leave empty to discard it.",
      owner: "Owner",
      ownerTooltip: "An organisation or a user.",
      type: "Kind",
      typeTooltip: "Which repositories of this owner to list.",
      "type.all": "All",
      "type.public": "Public",
      "type.private": "Private",
      "type.forks": "Forks",
      "type.sources": "Sources",
      "type.member": "Member of",
      limit: "Maximum number of results",
      limitTooltip: "Stops reading once this many items have been collected. Leave empty for the page budget of the configuration.",
      state: "State",
      stateTooltip: "Which issues to include.",
      "state.open": "Open",
      "state.closed": "Closed",
      "state.all": "All",
      labels: "Labels",
      labelsTooltip: "Comma separated. On a list action this filters: only issues carrying all of them come back.",
      assignee: "Assignee",
      assigneeTooltip: "A GitHub login. Use none for issues nobody is assigned to, or * for any.",
      creator: "Created by",
      creatorTooltip: "A GitHub login.",
      since: "Changed since",
      sinceTooltip: "Only issues updated after this moment, as an ISO 8601 timestamp.",
      issueNumber: "Issue number",
      issueNumberTooltip: "The number in the issue URL. A pull request has one too, and it works here.",
      includeComments: "Include comments",
      includeCommentsTooltip: "Costs an extra call, and can be a great deal of text on a long discussion.",
      includeTimeline: "Include timeline",
      includeTimelineTooltip: "Label changes, cross references and commits. This is where an existing pull request for this issue shows up.",
      query: "Query",
      queryTooltip: "GitHub's own search syntax. Note the search index lags writes by up to a few minutes.",
      sort: "Sort by",
      sortTooltip: "For example created, updated or comments. Leave empty for best match.",
      order: "Order",
      orderTooltip: "Only has an effect together with a sort field.",
      "order.": "Leave unchanged",
      "order.desc": "Descending",
      "order.asc": "Ascending",
      issueTitle: "Title",
      issueTitleTooltip: "The title.",
      body: "Body",
      bodyTooltip: "Markdown. Usually a process variable, for example pv:reviewReply.",
      newLabels: "Labels",
      newLabelsTooltip: "Comma separated.",
      assignees: "Assignees",
      assigneesTooltip: "Comma separated GitHub logins.",
      newTitle: "Title",
      newTitleTooltip: "Leave empty to leave the title as it is.",
      newBody: "Body",
      newBodyTooltip: "Markdown. Leave empty to leave the description as it is.",
      newState: "New state",
      newStateTooltip: "Leave empty to leave the state as it is. Closing a pull request here does not merge it.",
      "state.": "Leave unchanged",
      stateReason: "Reason",
      stateReasonTooltip: "Why the issue is being closed or reopened.",
      "stateReason.": "Leave unchanged",
      "stateReason.completed": "Done",
      "stateReason.not_planned": "Not planned",
      "stateReason.reopened": "Reopened",
      addLabels: "Add labels",
      addLabelsTooltip: "Comma separated. Added to whatever is already there, rather than replacing it.",
      removeLabels: "Remove labels",
      removeLabelsTooltip: "Comma separated. A label that is not there is not an error.",
      addAssignees: "Add assignees",
      addAssigneesTooltip: "Comma separated GitHub logins.",
      removeAssignees: "Remove assignees",
      removeAssigneesTooltip: "Comma separated GitHub logins.",
      prState: "State",
      prStateTooltip: "Which pull requests to include.",
      baseFilter: "Target branch",
      baseFilterTooltip: "Filters on the branch the changes are going into.",
      headFilter: "Source branch",
      headFilterTooltip: "Filters on the branch the changes come from.",
      pullRequestNumber: "Pull request number",
      pullRequestNumberTooltip: "The number in the pull request URL.",
      includeFiles: "Include changed files",
      includeFilesTooltip: "Filenames and line counts, not the diff itself.",
      includeReviews: "Include reviews",
      includeReviewsTooltip: "The approve and request-changes verdicts, with the text typed into them.",
      includeChecks: "Include check status",
      includeChecksTooltip: "Whether the head commit is green, across check runs and commit statuses.",
      head: "Source branch",
      headTooltip: "The branch holding the changes. It has to exist and to be ahead of the target.",
      base: "Target branch",
      baseTooltip: "Leave empty for the repository's own default branch — not every repository calls it main.",
      draft: "Draft",
      draftTooltip: "A draft pull request cannot be merged and does not ask anybody for a review.",
      newBase: "Target branch",
      newBaseTooltip: "Leave empty to leave the target branch as it is.",
      draftState: "Draft",
      draftStateTooltip: "On moves the pull request back to draft; off marks it ready for review.",
      mergeMethod: "Merge method",
      mergeMethodTooltip: "The method has to be one the repository allows, or GitHub refuses the merge.",
      "mergeMethod.merge": "Merge commit",
      "mergeMethod.squash": "Squash and merge",
      "mergeMethod.rebase": "Rebase and merge",
      commitTitle: "Commit title",
      commitTitleTooltip: "Leave empty for the title GitHub would generate.",
      commitMessage: "Commit message",
      commitMessageTooltip: "Leave empty for the message GitHub would generate.",
      expectedHeadSha: "Expected head commit",
      expectedHeadShaTooltip: "Worth filling in: GitHub refuses the merge when the branch moved since it was last read, instead of merging a commit nobody reviewed.",
      event: "Verdict",
      eventTooltip: "What kind of review to submit.",
      "event.APPROVE": "Approve",
      "event.REQUEST_CHANGES": "Request changes",
      "event.COMMENT": "Comment",
      reviewBody: "Body",
      reviewBodyTooltip: "Required for a comment or a request for changes; optional on an approval.",
      reviewers: "Reviewers",
      reviewersTooltip: "Comma separated GitHub logins. Somebody cannot be asked to review their own pull request.",
      teamReviewers: "Reviewing teams",
      teamReviewersTooltip: "Comma separated team slugs, without the organisation.",
      onlyUnresolved: "Only unresolved",
      onlyUnresolvedTooltip: "Leave on to work through open feedback: without it the same answered remarks come back on every pass.",
      commentId: "Comment",
      commentIdTooltip: "The numeric id of any comment in the thread, as returned by List review threads.",
      threadId: "Thread",
      threadIdTooltip: "The thread's id, as returned by List review threads. Not the same as a comment id.",
      resolve: "Resolve",
      resolveTooltip: "On marks the conversation resolved; off reopens it.",
      name: "Name",
      nameTooltip: "The label name, exactly as it should appear.",
      color: "Colour",
      colorTooltip: "Six hex digits. A leading # is accepted and stripped.",
      labelDescription: "Description",
      labelDescriptionTooltip: "Shown when somebody hovers over the label.",
      ref: "Commit, branch or tag",
      refTooltip: "A commit sha is the precise answer; a branch name reports whatever is at its tip right now.",
      branch: "Branch",
      branchTooltip: "Filters on the branch the run was for.",
      runStatus: "Status",
      runStatusTooltip: "For example completed, in_progress, failure or success.",
      runEvent: "Triggered by",
      runEventTooltip: "Filters on what started the run, for example push or pull_request.",
      runId: "Run",
      runIdTooltip: "The numeric id of the workflow run.",
      includeJobs: "Include jobs",
      includeJobsTooltip: "Adds every job of the run and, separately, the ones that failed and which of their steps did.",
      jobId: "Job",
      jobIdTooltip: "The numeric id of the job, as returned by Get workflow run.",
      maxLines: "Number of lines",
      maxLinesTooltip: "The tail of the log is kept: a failing job says why it failed at the end.",
      onlyFailed: "Only failed jobs",
      onlyFailedTooltip: "Off re-runs the whole workflow, which costs the full build.",
      path: "Path",
      pathTooltip: "Relative to the root of the repository. A directory lists its entries.",
      fileRef: "Commit, branch or tag",
      fileRefTooltip: "Leave empty for the repository's default branch.",
      writePath: "Path",
      writePathTooltip: "Relative to the root of the repository. Directories along the way are created.",
      content: "Content",
      contentTooltip: "The text to commit. Use a resource instead for anything that is not text.",
      resourceId: "Resource",
      resourceIdTooltip: "A file in temporary resource storage, by process variable. This is the way to commit an image. Give either this or content, not both.",
      writeBranch: "Branch",
      writeBranchTooltip: "Leave empty for the repository's default branch. The commit lands straight on it, with no pull request in between.",
      expectedSha: "Expected blob sha",
      expectedShaTooltip: "Leave empty and the existing file is looked up and replaced. Fill it in to refuse a file that changed since it was read.",
      branchName: "Branch name",
      branchNameTooltip: "Without refs/heads/. A branch that already exists is reported as it stands, not an error.",
      fromRef: "Branch off",
      fromRefTooltip: "A branch, tag or commit. Leave empty for the repository's default branch.",
      projectId: "Project",
      projectIdTooltip: "The node id of the project, as returned by Get project items.",
      itemId: "Card",
      itemIdTooltip: "The node id of the card on the board, as returned by Get project items.",
      fieldId: "Field",
      fieldIdTooltip: "The node id of the field, as returned by Get project items.",
      valueType: "Kind of value",
      valueTypeTooltip: "A single select and an iteration take the id of the option, not its label.",
      "valueType.text": "Text",
      "valueType.number": "Number",
      "valueType.date": "Date",
      "valueType.singleSelectOptionId": "Single select option",
      "valueType.iterationId": "Iteration",
      value: "Value",
      valueTooltip: "What to set the field to.",
      method: "Method",
      methodTooltip: "Leave on GET to read.",
      "method.GET": "GET (read)",
      "method.POST": "POST",
      "method.PATCH": "PATCH",
      "method.PUT": "PUT",
      "method.DELETE": "DELETE",
      restPath: "Path",
      restPathTooltip: "Relative to the REST root of this configuration, for example /repos/ritense/coworker-plugin/releases.",
      restBody: "Body",
      restBodyTooltip: "JSON. Leave empty for a request without one.",
      graphqlQuery: "Query",
      graphqlQueryTooltip: "A GraphQL query or mutation.",
      variables: "Variables",
      variablesTooltip: "JSON object of the query variables. Leave empty for a query without any.",
    },
  },
};

export {githubPluginSpecification};
